### PR TITLE
use .zip archive for nt

### PR DESCRIPTION
**Pull request by its-monotype**

### CODE REVIEW

**Comment by dennisvang** [comment]
Sorry for your trouble, but `zip` is not supported, and we would like to keep it that way.

If you really want to use `zip`, it is a small step to create a `.zip` from the `.tar.gz`, as part of your build workflow, as explained [here][1].

Moreover, you PR makes over 900 changes in 21 files. Most of this looks like unrelated changes in code style etc...

[1]: https://github.com/dennisvang/tufup/issues/43#issuecomment-1257581825

**Comment by its-monotype** [comment]
@dennisvang I also wanted to clarify why you do not want to add support for .zip archives, as far as I remember, a .zip archive was available in PyUpdater and this is not difficult to implement, just add to shutil.make_archive(format="zip" if os.name == " nt" else "gztar"). Maybe .zip. Is .tar.gz more convenient, or is it lighter, or is it common to use it with tuf? I'm not very good at this.

> Moreover, you PR makes over 900 changes in 21 files. Most of this looks like unrelated changes in code style etc...
Yes, I'm sorry for that, it's just that in your projects there were no settings for the linter and formatter. By default I have black and flake8 installed and these tools have all automatically formatted all the code :D.

**Comment by dennisvang** [comment]
> I also wanted to clarify why you do not want to add support for .zip archives, as far as I remember, a .zip archive was available in PyUpdater and this is not difficult to implement, ...

@its-monotype Support is limited to `.tar.gz` because that is sufficient to make `tufup` work, and `tar` is available on all supported platforms. In fact, you should probably consider this to be an internal detail of `tufup`.

The choice of format for the initial distribution of an app, i.e. how the end-user obtains and installs your app for the very first time, falls entirely outside the scope of `tufup`. In the end, `tufup` just packs your application bundle into a `.tar.gz` archive. You can choose to unpack this archive an re-pack into `.zip`, or create an installer that unpacks the `.tar.gz` directly, as explained in my previous [comment][1], or you could simply package your application bundle into a `.zip` archive directly from your bundle dir.

`PyUpdater` did indeed support `zip` archives, but it also prescribed the use of `PyInstaller` to bundle the app. Tufup, on the other hand, does not care how you bundle your app. It works with PyInstaller bundles, but also with any other bundle of files. It just gzips a bundle of files and delivers it, regardless of how the bundle was created.

[1]: https://github.com/dennisvang/tufup/issues/43#issuecomment-1257798895

**Comment by its-monotype** [comment]
@dennisvang Well, now I understand the philosophy of tufup. I'm really glad you're creating an auto-update framework because pyupdater is no longer supported and I haven't found any easy alternatives. I just, as a developer, want to use a ready-made tool that will help me implement auto-update functionality in my application; I don't want to write auto-update logic from scratch because it's not a top priority. As an absolute beginner in auto-updates, it is difficult for me to figure it out, so thanks for your help. And also glad that tufup, unlike pyupdater, does not care how you bundle your app. I sincerely hope that you will continue to develop tufup and I want to help with that as well. I also want to recommend that you make more detailed documentation because it is difficult for a beginner to understand this. By the way, you can use https://docsify.js.org/#/, well, this is up to you. And also I am very glad that you have tufup-example, but I would also like to see either a guide or more examples of how exactly you can create a server in production that will serve the repository and to regularly re-sign the timestamp metadata, you already mentioned that this is possible do it with cron and I know what it is but I don’t understand what I need to do exactly how to re-sign this timestamp and especially I don’t understand how to deploy it to a remote server, I also might like to use AWS S3 to upload update archives there for tufup and .zip archives that will be returned to the site for download by users on the site.

**Comment by dennisvang** [comment]
@its-monotype Thanks for your kind words. :-)

I agree that the documentation is terrible at the moment. We're planning to work on that, but are a little short on time right now.

Regarding the server setup, I am aware this can be very difficult to understand. However, we cannot start giving detailed advice on server setup, because this is far outside the scope for `tufup`. It is very implementation specific, and there are just too many things to consider.

If you're thinking about AWS S3 to serve your files, you could configure a server to read the files from S3, sign them periodically, and upload them again to S3. A typical solution would be to use EC2, perhaps through EB, to set up the server. Perhaps you could do a serverless solution using AWS Lambda, or AWS Batch, although I have no experience with those. I cannot give more detail, but there's a lot of useful examples on the web.

**Comment by its-monotype** [comment]
@dennisvang I once created an application on electron and auto-updates there as simple as possible, I would like to have such a cool alternative in python. Maybe something will help you, maybe this is an example: https://www.electron.build/auto-update.html

**Pull request closed without merging**
